// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgauejgFyJdK-UtvK3mKc7M7lnjs6-cu4',
    appId: '1:71530923889:android:0e3915f5886ccb7de298d0',
    messagingSenderId: '71530923889',
    projectId: 't7kem-al7an-c4a5f',
    storageBucket: 't7kem-al7an-c4a5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGUyeWmu4VN8bgFozQPrbLP7FbJSU2TI',
    appId: '1:71530923889:ios:1e66dec02301fbc8e298d0',
    messagingSenderId: '71530923889',
    projectId: 't7kem-al7an-c4a5f',
    storageBucket: 't7kem-al7an-c4a5f.firebasestorage.app',
    iosBundleId: 'com.example.t7kemAl7an',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRCPtP7JazOJSCGx6i4jwYTJ_9M0lx-I',
    appId: '1:71530923889:web:1b30c5f35535953de298d0',
    messagingSenderId: '71530923889',
    projectId: 't7kem-al7an-c4a5f',
    authDomain: 't7kem-al7an-c4a5f.firebaseapp.com',
    storageBucket: 't7kem-al7an-c4a5f.firebasestorage.app',
    measurementId: 'G-GRE9ZWZZFD',
  );

}